### ISSUE TITLE
Orte Gievenbeck: Rüschhausweg/ Ortsmitte und Gremmendorf: Gremmendorfer Weg

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/wo-ist-markt#2]
Für die Märkte Gievenbeck: Rüschhausweg/ Ortsmitte und Gremmendorf: Gremmendorfer Weg kann ich nichts finden. Wer da lokales Wissen hat: Eintragen!

**Comment by ubergesundheit** [comment]
Gremmendorf: https://github.com/wo-ist-markt/wo-ist-markt.github.io/pull/8, danke @TinoM

**Comment by chk1** [comment]
Der Wochenmarkt in Gievenbeck ist hier: http://www.openstreetmap.org/node/1092306403

>donnerstags 14.00 - 18.00 Uhr

http://www.muenster.de/stadt/maerkte/markt.html
